# .github/workflows/deploy-s3.yml
name: Deploy to S3

on:
  push:
    branches:
      - main
    paths:
      - 'dags/scripts/job_bronze_to_silver.py'
  pull_request:
    branches:
      - main
    paths:
      - 'dags/scripts/job_bronze_to_silver.py'
  workflow_dispatch:  # Rodar manualmente
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload para S3
        run: |
          aws s3 cp ./dags/scripts/job_bronze_to_silver.py s3://${{ secrets.S3_BUCKET }}/scripts/job_bronze_to_silver.py
